export const ASYNC_STORAGE_ID_TOKEN_KEY = 'userToken'
export const ERROR_ALERT_TITLE = 'Error'
export const DRAGGABLE_LIST_COMPONENT_DELAY = 0.5
export const DRAGGABLE_LIST_CARD_WIDTH_FACTOR = -10
export const DRAGGABLE_LIST_CARD_HEIGHT = 70
