name: client

on: push

jobs:
  client-format:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 12

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: client/node_modules
          key: ${{ runner.os }}-cache

      - name: Install dependencies
        working-directory: ./client
        run: yarn

      - name: Check formatting
        working-directory: ./client
        run: yarn format:check

  client-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 12

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: client/node_modules
          key: ${{ runner.os }}-cache

      - name: Install dependencies
        working-directory: ./client
        run: yarn

      - name: Install root dependencies
        working-directory: ./
        run: yarn

      - name: Run linter
        working-directory: ./client
        run: yarn lint